/*
 * Automatically generated by "tools/bmp_logo"
 *
 * DO NOT EDIT
 *
 */

#ifndef __BMP_LOGO_H__
#define __BMP_LOGO_H__

#define BMP_LOGO_WIDTH		300
#define BMP_LOGO_HEIGHT		300
#define BMP_LOGO_COLORS		0
#define BMP_LOGO_OFFSET		16

#define BMP_LOGO_NBIT		24

extern unsigned short bmp_logo_palette[];
extern unsigned int bmp_logo_bitmap[];

#endif /* __BMP_LOGO_H__ */
