/*
 * Automatically generated by "tools/bmp_logo"
 *
 * DO NOT EDIT
 *
 */

#ifndef __BMP_LOGO_H__
#define __BMP_LOGO_H__

#define BMP_LOGO_WIDTH		400
#define BMP_LOGO_HEIGHT		240
#define BMP_LOGO_COLORS		240
#define BMP_LOGO_OFFSET		16

#define BMP_LOGO_NBIT		16

extern unsigned short bmp_logo_palette[];
extern unsigned short bmp_logo_bitmap[];

#endif /* __BMP_LOGO_H__ */
