/*-----------------------------------------------------------------------------
  This confidential and proprietary software/information may be used only
  as authorized by a licensing agreement from Apical Limited

  (C) COPYRIGHT 2011 - 2015 Apical Limited
  ALL RIGHTS RESERVED

  The entire notice above must be reproduced on all authorized
  copies and copies may only be made to the extent permitted
  by a licensing agreement from Apical Limited.
  -----------------------------------------------------------------------------*/

#ifndef __APICAL_SENSOR_CONFIG_H__
#define __APICAL_SENSOR_CONFIG_H__


#define SENSOR_BUS_ADDR_SHIFT 0
#define ISP_SENSOR_DRIVER_DONGWOON 0
#define SENSOR_IMAGE_WIDTH_PREVIEW 1920
#define LOG2_SENSOR_DGAIN_MAXIMUM 0
#define SENSOR_OUTPUT_BITS 12
#define SENSOR_BOARD_MASTER_CLOCK 24000
#define SENSOR_MID_MULT 1
#define SENSOR_IMAGE_HEIGHT_PREVIEW 1080
#define SENSOR_SEQUENCE_NAME default
#define FULL_EXTRA_HEIGHT 0
#define ISP_IMAGE_WIDTH SENSOR_IMAGE_WIDTH
#define SENSOR_SEQUENCE_FULL_RES_MAX_FPS 0
#define ISP_SENSOR_DRIVER_NULL 0
#define SENSOR_EXP_NUMBER 1
#define SENSOR_INTEGRATION_TIME_APPLY_DELAY 2
#define RESOLUTION_CHANGE_ENABLED 1
#define SENSOR_TOTAL_WIDTH 2200
#define SENSOR_SEQUENCE_FULL_RES_HALF_FPS 2
#define SPI_CLOCK_DIV 40
#define SENSOR_MAX_INTEGRATION_TIME 1125
#define SENSOR_MIN_INTEGRATION_TIME_NATIVE SENSOR_MIN_INTEGRATION_TIME
#define SENSOR_DIGITAL_GAIN_APPLY_DELAY 2
#define SENSOR_TOTAL_HEIGHT 1125
#define SENSOR_TOTAL_WIDTH_PREVIEW 3264
#define SENSOR_MAX_INTEGRATION_TIME_PREVIEW 2586-14
#define ISP_SENSOR_DRIVER_LC898201 0
#define ISP_SENSOR_DRIVER_ROHM 0
#define SENSOR_IMAGE_HEIGHT 1080
#define SENSOR_TOTAL_HEIGHT_PREVIEW 2586
#define SENSOR_AF_MOVE_DELAY 20
#define SENSOR_LONG_SHIFT 0
#define SENSOR_MID_SHIFT 0
#define ISP_SENSOR_DRIVER_AD5821 0
#define SPI_CONTROL_MASK (RX_NEG_MSK|(CHAR_LEN_MSK&24)|AUTO_SS_MSK|LSB_MSK)
#define SENSOR_DAY_LIGHT_INTEGRATION_TIME_LIMIT 300
#define SENSOR_MAX_INTEGRATION_TIME_LIMIT 1125
#define SENSOR_MIN_INTEGRATION_TIME 1
#define SENSOR_SEQUENCE_PREVIEW_RES_MAX_FPS 1
#define SENSOR_IMAGE_WIDTH_FULL 3264
#define LOG2_SENSOR_AGAIN_MAXIMUM 0
#define SENSOR_LONG_MULT 1
#define PREVIEW_EXTRA_WIDTH 0
#define SENSOR_IMAGE_WIDTH 1920
#define FULL_EXTRA_WIDTH 0
#define SENSOR_BUS spi
#define SENSOR_BLACK_LEVEL_CORRECTION 0
#define SENSOR_IMAGE_HEIGHT_FULL 2448
#define ISP_IMAGE_HEIGHT SENSOR_IMAGE_HEIGHT
#define SENSOR_ANALOG_GAIN_APPLY_DELAY 2
#define SENSOR_SAMPLE_MASK 1
#define SENSOR_MAX_INTEGRATION_TIME_NATIVE SENSOR_MAX_INTEGRATION_TIME
#define SENSOR_ENDIAN_MASK 1
#define PREVIEW_EXTRA_HEIGHT 0
#define SENSOR_SEQUENCE_PREVIEW_RES_HALF_FPS 3
#define SENSOR_BUS_ADDRESS 0
#endif
