#ifndef __APICAL_ISP_CALIBRATIONS_H__
#define __APICAL_ISP_CALIBRATIONS_H__


// ------------------------------------------------------------------------------ //
//     This confidential and proprietary software/information may be used only    //
//        as authorized by a licensing agreement from Apical Limited              //
//                                                                                //
//                   (C) COPYRIGHT 2014 Apical Limited                            //
//                          ALL RIGHTS RESERVED                                   //
//                                                                                //
//      The entire notice above must be reproduced on all authorized              //
//       copies and copies may only be made to the extent permitted               //
//             by a licensing agreement from Apical Limited.                      //
//                                                                                //
// ------------------------------------------------------------------------------ //

#include "apical_types.h"

enum EWDRModeID {
	WDR_MODE_LINEAR = 0,
	WDR_MODE_FS_HDR,
	WDR_MODE_NATIVE,
	WDR_MODE_FS_LIN,
	WDR_MODE_COUNT
} ;


#define WDR_MODE_POSITION ( WDR_MODE_FS_HDR )

// when you describe luts for WDR modes
// use START and STOP dummy defines to avoid a collision with
// other lut indexes
enum ECalibrationID {
	// isp calibrations
	_CALIBRATION_LUTS_START_INDEX = 0, // do not change this. MUST be always zero.
	// noise profile lut
	_CALIBRATION_NOISE_PROFILE_START,
	_CALIBRATION_NOISE_PROFILE_LINEAR  = _CALIBRATION_NOISE_PROFILE_START + WDR_MODE_LINEAR,
	_CALIBRATION_NOISE_PROFILE_FS_HDR  = _CALIBRATION_NOISE_PROFILE_START + WDR_MODE_FS_HDR,
	_CALIBRATION_NOISE_PROFILE_NATIVE  = _CALIBRATION_NOISE_PROFILE_START + WDR_MODE_NATIVE,
	_CALIBRATION_NOISE_PROFILE_FS_LIN  = _CALIBRATION_NOISE_PROFILE_START + WDR_MODE_FS_LIN,
	_CALIBRATION_NOISE_PROFILE_STOP    = _CALIBRATION_NOISE_PROFILE_START + WDR_MODE_COUNT,
	// demosaic
	_CALIBRATION_DEMOSAIC_START,
	_CALIBRATION_DEMOSAIC_LINEAR  = _CALIBRATION_DEMOSAIC_START + WDR_MODE_LINEAR,
	_CALIBRATION_DEMOSAIC_FS_HDR  = _CALIBRATION_DEMOSAIC_START + WDR_MODE_FS_HDR,
	_CALIBRATION_DEMOSAIC_NATIVE  = _CALIBRATION_DEMOSAIC_START + WDR_MODE_NATIVE,
	_CALIBRATION_DEMOSAIC_FS_LIN  = _CALIBRATION_DEMOSAIC_START + WDR_MODE_FS_LIN,
	_CALIBRATION_DEMOSAIC_STOP    = _CALIBRATION_DEMOSAIC_START + WDR_MODE_COUNT,
	// gamma linear
	_CALIBRATION_GAMMA_START,
	_CALIBRATION_GAMMA_LINEAR  = _CALIBRATION_GAMMA_START + WDR_MODE_LINEAR,
	_CALIBRATION_GAMMA_FS_HDR  = _CALIBRATION_GAMMA_START + WDR_MODE_FS_HDR,
	_CALIBRATION_GAMMA_NATIVE  = _CALIBRATION_GAMMA_START + WDR_MODE_NATIVE,
	_CALIBRATION_GAMMA_FS_LIN  = _CALIBRATION_GAMMA_START + WDR_MODE_FS_LIN,
	_CALIBRATION_GAMMA_STOP    = _CALIBRATION_GAMMA_START + WDR_MODE_COUNT,
	// gamma be 0
	_CALIBRATION_GAMMA_BE_0_START,
	_CALIBRATION_GAMMA_BE_0_FS_HDR  = _CALIBRATION_GAMMA_BE_0_START + WDR_MODE_FS_HDR,
	_CALIBRATION_GAMMA_BE_0_NATIVE  = _CALIBRATION_GAMMA_BE_0_START + WDR_MODE_NATIVE,
	_CALIBRATION_GAMMA_BE_0_FS_LIN  = _CALIBRATION_GAMMA_BE_0_START + WDR_MODE_FS_LIN,
	_CALIBRATION_GAMMA_BE_0_STOP    = _CALIBRATION_GAMMA_BE_0_START + WDR_MODE_COUNT,
	// gamma be 1
	_CALIBRATION_GAMMA_BE_1_START,
	_CALIBRATION_GAMMA_BE_1_LINEAR  = _CALIBRATION_GAMMA_BE_1_START + WDR_MODE_LINEAR,
	_CALIBRATION_GAMMA_BE_1_FS_HDR  = _CALIBRATION_GAMMA_BE_1_START + WDR_MODE_FS_HDR,
	_CALIBRATION_GAMMA_BE_1_NATIVE  = _CALIBRATION_GAMMA_BE_1_START + WDR_MODE_NATIVE,
	_CALIBRATION_GAMMA_BE_1_FS_LIN  = _CALIBRATION_GAMMA_BE_1_START + WDR_MODE_FS_LIN,
	_CALIBRATION_GAMMA_BE_1_STOP    = _CALIBRATION_GAMMA_BE_1_START + WDR_MODE_COUNT,
	// gamme fe 0
	_CALIBRATION_GAMMA_FE_0_START,
	_CALIBRATION_GAMMA_FE_0_LINEAR  = _CALIBRATION_GAMMA_FE_0_START + WDR_MODE_LINEAR,
	_CALIBRATION_GAMMA_FE_0_FS_HDR  = _CALIBRATION_GAMMA_FE_0_START + WDR_MODE_FS_HDR,
	_CALIBRATION_GAMMA_FE_0_NATIVE  = _CALIBRATION_GAMMA_FE_0_START + WDR_MODE_NATIVE,
	_CALIBRATION_GAMMA_FE_0_FS_LIN  = _CALIBRATION_GAMMA_FE_0_START + WDR_MODE_FS_LIN,
	_CALIBRATION_GAMMA_FE_0_STOP    = _CALIBRATION_GAMMA_FE_0_START + WDR_MODE_COUNT,
	// gamma fe 1
	_CALIBRATION_GAMMA_FE_1_START,
	_CALIBRATION_GAMMA_FE_1_LINEAR  = _CALIBRATION_GAMMA_FE_1_START + WDR_MODE_LINEAR,
	_CALIBRATION_GAMMA_FE_1_FS_HDR  = _CALIBRATION_GAMMA_FE_1_START + WDR_MODE_FS_HDR,
	_CALIBRATION_GAMMA_FE_1_NATIVE  = _CALIBRATION_GAMMA_FE_1_START + WDR_MODE_NATIVE,
	_CALIBRATION_GAMMA_FE_1_FS_LIN  = _CALIBRATION_GAMMA_FE_1_START + WDR_MODE_FS_LIN,
	_CALIBRATION_GAMMA_FE_1_STOP    = _CALIBRATION_GAMMA_FE_1_START + WDR_MODE_COUNT,
	// iridix exposure value limits
	_CALIBRATION_IRIDIX_EV_LIM_NO_STR_START,
	_CALIBRATION_IRIDIX_EV_LIM_NO_STR_LINEAR = _CALIBRATION_IRIDIX_EV_LIM_NO_STR_START + WDR_MODE_LINEAR,
	_CALIBRATION_IRIDIX_EV_LIM_NO_STR_FS_HDR = _CALIBRATION_IRIDIX_EV_LIM_NO_STR_START + WDR_MODE_FS_HDR,
	_CALIBRATION_IRIDIX_EV_LIM_NO_STR_NATIVE = _CALIBRATION_IRIDIX_EV_LIM_NO_STR_START + WDR_MODE_NATIVE,
	_CALIBRATION_IRIDIX_EV_LIM_NO_STR_FS_LIN = _CALIBRATION_IRIDIX_EV_LIM_NO_STR_START + WDR_MODE_FS_LIN,
	_CALIBRATION_IRIDIX_EV_LIM_NO_STR_STOP   = _CALIBRATION_IRIDIX_EV_LIM_NO_STR_START + WDR_MODE_COUNT,
	// auto exposure correction
	_CALIBRATION_AE_CORRECTION_START,
	_CALIBRATION_AE_CORRECTION_LINEAR = _CALIBRATION_AE_CORRECTION_START + WDR_MODE_LINEAR,
	_CALIBRATION_AE_CORRECTION_FS_HDR = _CALIBRATION_AE_CORRECTION_START + WDR_MODE_FS_HDR,
	_CALIBRATION_AE_CORRECTION_NATIVE = _CALIBRATION_AE_CORRECTION_START + WDR_MODE_NATIVE,
	_CALIBRATION_AE_CORRECTION_FS_LIN = _CALIBRATION_AE_CORRECTION_START + WDR_MODE_FS_LIN,
	_CALIBRATION_AE_CORRECTION_STOP   = _CALIBRATION_AE_CORRECTION_START + WDR_MODE_COUNT,
	// sinter strength 0
	_CALIBRATION_SINTER_STRENGTH_START,
	_CALIBRATION_SINTER_STRENGTH_LINEAR = _CALIBRATION_SINTER_STRENGTH_START + WDR_MODE_LINEAR,
	_CALIBRATION_SINTER_STRENGTH_FS_HDR = _CALIBRATION_SINTER_STRENGTH_START + WDR_MODE_FS_HDR,
	_CALIBRATION_SINTER_STRENGTH_NATIVE = _CALIBRATION_SINTER_STRENGTH_START + WDR_MODE_NATIVE,
	_CALIBRATION_SINTER_STRENGTH_FS_LIN = _CALIBRATION_SINTER_STRENGTH_START + WDR_MODE_FS_LIN,
	_CALIBRATION_SINTER_STRENGTH_STOP   = _CALIBRATION_SINTER_STRENGTH_START + WDR_MODE_COUNT,
	// sinter strength 1
	_CALIBRATION_SINTER_STRENGTH1_START,
	_CALIBRATION_SINTER_STRENGTH1_LINEAR = _CALIBRATION_SINTER_STRENGTH1_START + WDR_MODE_LINEAR,
	_CALIBRATION_SINTER_STRENGTH1_FS_HDR = _CALIBRATION_SINTER_STRENGTH1_START + WDR_MODE_FS_HDR,
	_CALIBRATION_SINTER_STRENGTH1_NATIVE = _CALIBRATION_SINTER_STRENGTH1_START + WDR_MODE_NATIVE,
	_CALIBRATION_SINTER_STRENGTH1_FS_LIN = _CALIBRATION_SINTER_STRENGTH1_START + WDR_MODE_FS_LIN,
	_CALIBRATION_SINTER_STRENGTH1_STOP   = _CALIBRATION_SINTER_STRENGTH1_START + WDR_MODE_COUNT,
	// sinter thresh 1
	_CALIBRATION_SINTER_THRESH1_START,
	_CALIBRATION_SINTER_THRESH1_LINEAR = _CALIBRATION_SINTER_THRESH1_START + WDR_MODE_LINEAR,
	_CALIBRATION_SINTER_THRESH1_FS_HDR = _CALIBRATION_SINTER_THRESH1_START + WDR_MODE_FS_HDR,
	_CALIBRATION_SINTER_THRESH1_NATIVE = _CALIBRATION_SINTER_THRESH1_START + WDR_MODE_NATIVE,
	_CALIBRATION_SINTER_THRESH1_FS_LIN = _CALIBRATION_SINTER_THRESH1_START + WDR_MODE_FS_LIN,
	_CALIBRATION_SINTER_THRESH1_STOP   = _CALIBRATION_SINTER_THRESH1_START + WDR_MODE_COUNT,
	// thresh 4
	_CALIBRATION_SINTER_THRESH4_START,
	_CALIBRATION_SINTER_THRESH4_LINEAR = _CALIBRATION_SINTER_THRESH4_START + WDR_MODE_LINEAR,
	_CALIBRATION_SINTER_THRESH4_FS_HDR = _CALIBRATION_SINTER_THRESH4_START + WDR_MODE_FS_HDR,
	_CALIBRATION_SINTER_THRESH4_NATIVE = _CALIBRATION_SINTER_THRESH4_START + WDR_MODE_NATIVE,
	_CALIBRATION_SINTER_THRESH4_FS_LIN = _CALIBRATION_SINTER_THRESH4_START + WDR_MODE_FS_LIN,
	_CALIBRATION_SINTER_THRESH4_STOP   = _CALIBRATION_SINTER_THRESH4_START + WDR_MODE_COUNT,
	// sharpening alt d
	_CALIBRATION_SHARP_ALT_D_START,
	_CALIBRATION_SHARP_ALT_D_LINEAR = _CALIBRATION_SHARP_ALT_D_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHARP_ALT_D_FS_HDR = _CALIBRATION_SHARP_ALT_D_START + WDR_MODE_FS_HDR,
	_CALIBRATION_SHARP_ALT_D_NATIVE = _CALIBRATION_SHARP_ALT_D_START + WDR_MODE_NATIVE,
	_CALIBRATION_SHARP_ALT_D_FS_LIN = _CALIBRATION_SHARP_ALT_D_START + WDR_MODE_FS_LIN,
	_CALIBRATION_SHARP_ALT_D_STOP   = _CALIBRATION_SHARP_ALT_D_START + WDR_MODE_COUNT,
	// sharpening alt ud
	_CALIBRATION_SHARP_ALT_UD_START,
	_CALIBRATION_SHARP_ALT_UD_LINEAR = _CALIBRATION_SHARP_ALT_UD_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHARP_ALT_UD_FS_HDR = _CALIBRATION_SHARP_ALT_UD_START + WDR_MODE_FS_HDR,
	_CALIBRATION_SHARP_ALT_UD_NATIVE = _CALIBRATION_SHARP_ALT_UD_START + WDR_MODE_NATIVE,
	_CALIBRATION_SHARP_ALT_UD_FS_LIN = _CALIBRATION_SHARP_ALT_UD_START + WDR_MODE_FS_LIN,
	_CALIBRATION_SHARP_ALT_UD_STOP   = _CALIBRATION_SHARP_ALT_UD_START + WDR_MODE_COUNT,
	// sharpening alt du
	_CALIBRATION_SHARP_ALT_DU_START,
	_CALIBRATION_SHARP_ALT_DU_LINEAR = _CALIBRATION_SHARP_ALT_DU_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHARP_ALT_DU_FS_HDR = _CALIBRATION_SHARP_ALT_DU_START + WDR_MODE_FS_HDR,
	_CALIBRATION_SHARP_ALT_DU_NATIVE = _CALIBRATION_SHARP_ALT_DU_START + WDR_MODE_NATIVE,
	_CALIBRATION_SHARP_ALT_DU_FS_LIN = _CALIBRATION_SHARP_ALT_DU_START + WDR_MODE_FS_LIN,
	_CALIBRATION_SHARP_ALT_DU_STOP   = _CALIBRATION_SHARP_ALT_DU_START + WDR_MODE_COUNT,
	// demosaic noise profile offset
	_CALIBRATION_DEMOSAIC_NP_OFFSET_START,
	_CALIBRATION_DEMOSAIC_NP_OFFSET_LINEAR = _CALIBRATION_DEMOSAIC_NP_OFFSET_START + WDR_MODE_LINEAR,
	_CALIBRATION_DEMOSAIC_NP_OFFSET_FS_HDR = _CALIBRATION_DEMOSAIC_NP_OFFSET_START + WDR_MODE_FS_HDR,
	_CALIBRATION_DEMOSAIC_NP_OFFSET_NATIVE = _CALIBRATION_DEMOSAIC_NP_OFFSET_START + WDR_MODE_NATIVE,
	_CALIBRATION_DEMOSAIC_NP_OFFSET_FS_LIN = _CALIBRATION_DEMOSAIC_NP_OFFSET_START + WDR_MODE_FS_LIN,
	_CALIBRATION_DEMOSAIC_NP_OFFSET_STOP   = _CALIBRATION_DEMOSAIC_NP_OFFSET_START + WDR_MODE_COUNT,
	// demosaic noise profile offset
	_CALIBRATION_SATURATION_STRENGTH_START,
	_CALIBRATION_SATURATION_STRENGTH_LINEAR = _CALIBRATION_SATURATION_STRENGTH_START + WDR_MODE_LINEAR,
	_CALIBRATION_SATURATION_STRENGTH_FS_HDR = _CALIBRATION_SATURATION_STRENGTH_START + WDR_MODE_FS_HDR,
	_CALIBRATION_SATURATION_STRENGTH_NATIVE = _CALIBRATION_SATURATION_STRENGTH_START + WDR_MODE_NATIVE,
	_CALIBRATION_SATURATION_STRENGTH_FS_LIN = _CALIBRATION_SATURATION_STRENGTH_START + WDR_MODE_FS_LIN,
	_CALIBRATION_SATURATION_STRENGTH_STOP   = _CALIBRATION_SATURATION_STRENGTH_START + WDR_MODE_COUNT,
	// iridix strength
	_CALIBRATION_IRIDIX_STRENGTH_MAXIMUM_START,
	_CALIBRATION_IRIDIX_STRENGTH_MAXIMUM_LINEAR = _CALIBRATION_IRIDIX_STRENGTH_MAXIMUM_START + WDR_MODE_LINEAR,
	_CALIBRATION_IRIDIX_STRENGTH_MAXIMUM_WDR    = _CALIBRATION_IRIDIX_STRENGTH_MAXIMUM_START + WDR_MODE_POSITION,
	_CALIBRATION_IRIDIX_STRENGTH_MAXIMUM_STOP   = _CALIBRATION_IRIDIX_STRENGTH_MAXIMUM_START + WDR_MODE_COUNT,
	// sinter sad
	_CALIBRATION_SINTER_SAD_START,
	_CALIBRATION_SINTER_SAD_LINEAR = _CALIBRATION_SINTER_SAD_START + WDR_MODE_LINEAR,
	_CALIBRATION_SINTER_SAD_WDR    = _CALIBRATION_SINTER_SAD_START + WDR_MODE_POSITION,
	_CALIBRATION_SINTER_SAD_STOP   = _CALIBRATION_SINTER_SAD_START + WDR_MODE_COUNT,
	// sharpen fr
	_CALIBRATION_SHARPEN_FR_START,
	_CALIBRATION_SHARPEN_FR_LINEAR = _CALIBRATION_SHARPEN_FR_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHARPEN_FR_WDR    = _CALIBRATION_SHARPEN_FR_START + WDR_MODE_POSITION,
	_CALIBRATION_SHARPEN_FR_STOP   = _CALIBRATION_SHARPEN_FR_START + WDR_MODE_COUNT,
	// sharpen ds1
	_CALIBRATION_SHARPEN_DS1_START,
	_CALIBRATION_SHARPEN_DS1_LINEAR = _CALIBRATION_SHARPEN_DS1_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHARPEN_DS1_WDR    = _CALIBRATION_SHARPEN_DS1_START + WDR_MODE_POSITION,
	_CALIBRATION_SHARPEN_DS1_STOP   = _CALIBRATION_SHARPEN_DS1_START + WDR_MODE_COUNT,
	// sharpen ds2
	_CALIBRATION_SHARPEN_DS2_START,
	_CALIBRATION_SHARPEN_DS2_LINEAR = _CALIBRATION_SHARPEN_DS2_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHARPEN_DS2_WDR    = _CALIBRATION_SHARPEN_DS2_START + WDR_MODE_POSITION,
	_CALIBRATION_SHARPEN_DS2_STOP   = _CALIBRATION_SHARPEN_DS2_START + WDR_MODE_COUNT,
	// black level for r channel
	_CALIBRATION_BLACK_LEVEL_R_START,
	_CALIBRATION_BLACK_LEVEL_R_LINEAR = _CALIBRATION_BLACK_LEVEL_R_START + WDR_MODE_LINEAR,
	_CALIBRATION_BLACK_LEVEL_R_FS_HDR = _CALIBRATION_BLACK_LEVEL_R_START + WDR_MODE_FS_HDR,
	_CALIBRATION_BLACK_LEVEL_R_NATIVE = _CALIBRATION_BLACK_LEVEL_R_START + WDR_MODE_NATIVE,
	_CALIBRATION_BLACK_LEVEL_R_FS_LIN = _CALIBRATION_BLACK_LEVEL_R_START + WDR_MODE_FS_LIN,
	_CALIBRATION_BLACK_LEVEL_R_STOP   = _CALIBRATION_BLACK_LEVEL_R_START + WDR_MODE_COUNT,
	// black level for b channel
	_CALIBRATION_BLACK_LEVEL_B_START,
	_CALIBRATION_BLACK_LEVEL_B_LINEAR = _CALIBRATION_BLACK_LEVEL_B_START + WDR_MODE_LINEAR,
	_CALIBRATION_BLACK_LEVEL_B_FS_HDR = _CALIBRATION_BLACK_LEVEL_B_START + WDR_MODE_FS_HDR,
	_CALIBRATION_BLACK_LEVEL_B_NATIVE = _CALIBRATION_BLACK_LEVEL_B_START + WDR_MODE_NATIVE,
	_CALIBRATION_BLACK_LEVEL_B_FS_LIN = _CALIBRATION_BLACK_LEVEL_B_START + WDR_MODE_FS_LIN,
	_CALIBRATION_BLACK_LEVEL_B_STOP   = _CALIBRATION_BLACK_LEVEL_B_START + WDR_MODE_COUNT,
	// black level for gb channel
	_CALIBRATION_BLACK_LEVEL_GB_START,
	_CALIBRATION_BLACK_LEVEL_GB_LINEAR = _CALIBRATION_BLACK_LEVEL_GB_START + WDR_MODE_LINEAR,
	_CALIBRATION_BLACK_LEVEL_GB_FS_HDR = _CALIBRATION_BLACK_LEVEL_GB_START + WDR_MODE_FS_HDR,
	_CALIBRATION_BLACK_LEVEL_GB_NATIVE = _CALIBRATION_BLACK_LEVEL_GB_START + WDR_MODE_NATIVE,
	_CALIBRATION_BLACK_LEVEL_GB_FS_LIN = _CALIBRATION_BLACK_LEVEL_GB_START + WDR_MODE_FS_LIN,
	_CALIBRATION_BLACK_LEVEL_GB_STOP   = _CALIBRATION_BLACK_LEVEL_GB_START + WDR_MODE_COUNT,
	// black level for gr channel
	_CALIBRATION_BLACK_LEVEL_GR_START,
	_CALIBRATION_BLACK_LEVEL_GR_LINEAR = _CALIBRATION_BLACK_LEVEL_GR_START + WDR_MODE_LINEAR,
	_CALIBRATION_BLACK_LEVEL_GR_FS_HDR = _CALIBRATION_BLACK_LEVEL_GR_START + WDR_MODE_FS_HDR,
	_CALIBRATION_BLACK_LEVEL_GR_NATIVE = _CALIBRATION_BLACK_LEVEL_GR_START + WDR_MODE_NATIVE,
	_CALIBRATION_BLACK_LEVEL_GR_FS_LIN = _CALIBRATION_BLACK_LEVEL_GR_START + WDR_MODE_FS_LIN,
	_CALIBRATION_BLACK_LEVEL_GR_STOP   = _CALIBRATION_BLACK_LEVEL_GR_START + WDR_MODE_COUNT,
	// dp slope
	_CALIBRATION_DP_SLOPE_START,
	_CALIBRATION_DP_SLOPE_LINEAR  = _CALIBRATION_DP_SLOPE_START + WDR_MODE_LINEAR,
	_CALIBRATION_DP_SLOPE_FS_HDR  = _CALIBRATION_DP_SLOPE_START + WDR_MODE_FS_HDR,
	_CALIBRATION_DP_SLOPE_NATIVE  = _CALIBRATION_DP_SLOPE_START + WDR_MODE_NATIVE,
	_CALIBRATION_DP_SLOPE_FS_LIN  = _CALIBRATION_DP_SLOPE_START + WDR_MODE_FS_LIN,
	_CALIBRATION_DP_SLOPE_FS_STOP = _CALIBRATION_DP_SLOPE_START + WDR_MODE_COUNT,
	// dp threshold
	_CALIBRATION_DP_THRESHOLD_START,
	_CALIBRATION_DP_THRESHOLD_LINEAR = _CALIBRATION_DP_THRESHOLD_START + WDR_MODE_LINEAR,
	_CALIBRATION_DP_THRESHOLD_FS_HDR = _CALIBRATION_DP_THRESHOLD_START + WDR_MODE_FS_HDR,
	_CALIBRATION_DP_THRESHOLD_NATIVE = _CALIBRATION_DP_THRESHOLD_START + WDR_MODE_NATIVE,
	_CALIBRATION_DP_THRESHOLD_FS_LIN = _CALIBRATION_DP_THRESHOLD_START + WDR_MODE_FS_LIN,
	_CALIBRATION_DP_THRESHOLD_FS_STOP= _CALIBRATION_DP_THRESHOLD_START + WDR_MODE_COUNT,
	// AE_balanced calibration
	_CALIBRATION_AE_BALANCED_START,
	_CALIBRATION_AE_BALANCED_LINEAR = _CALIBRATION_AE_BALANCED_START + WDR_MODE_LINEAR,
	_CALIBRATION_AE_BALANCED_WDR    = _CALIBRATION_AE_BALANCED_START + WDR_MODE_POSITION,
	_CALIBRATION_AE_BALANCED_STOP   = _CALIBRATION_AE_BALANCED_START + WDR_MODE_COUNT,
	//AWB LUX Lut calibration
	_CALIBRATION_EVTOLUX_EV_LUT_START,
	_CALIBRATION_EVTOLUX_EV_LUT_LINEAR=_CALIBRATION_EVTOLUX_EV_LUT_START+WDR_MODE_LINEAR,
	_CALIBRATION_EVTOLUX_EV_LUT_FS_HDR=_CALIBRATION_EVTOLUX_EV_LUT_START+WDR_MODE_FS_HDR,
	_CALIBRATION_EVTOLUX_EV_LUT_NATIVE=_CALIBRATION_EVTOLUX_EV_LUT_START+WDR_MODE_NATIVE,
	_CALIBRATION_EVTOLUX_EV_LUT_FS_LIN=_CALIBRATION_EVTOLUX_EV_LUT_START+ WDR_MODE_FS_LIN,
	_CALIBRATION_EVTOLUX_EV_LUT_STOP=_CALIBRATION_EVTOLUX_EV_LUT_START+WDR_MODE_COUNT,
	// mesh shading for linear and wdr modes
	_CALIBRATION_SHADING_LS_A_R_START,
	_CALIBRATION_SHADING_LS_A_R_LINEAR = _CALIBRATION_SHADING_LS_A_R_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHADING_LS_A_R_WDR    = _CALIBRATION_SHADING_LS_A_R_START + WDR_MODE_POSITION,
	_CALIBRATION_SHADING_LS_A_R_STOP   = _CALIBRATION_SHADING_LS_A_R_START + WDR_MODE_COUNT,

	_CALIBRATION_SHADING_LS_A_G_START,
	_CALIBRATION_SHADING_LS_A_G_LINEAR = _CALIBRATION_SHADING_LS_A_G_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHADING_LS_A_G_WDR    = _CALIBRATION_SHADING_LS_A_G_START + WDR_MODE_POSITION,
	_CALIBRATION_SHADING_LS_A_G_STOP   = _CALIBRATION_SHADING_LS_A_G_START + WDR_MODE_COUNT,

	_CALIBRATION_SHADING_LS_A_B_START,
	_CALIBRATION_SHADING_LS_A_B_LINEAR = _CALIBRATION_SHADING_LS_A_B_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHADING_LS_A_B_WDR    = _CALIBRATION_SHADING_LS_A_B_START + WDR_MODE_POSITION,
	_CALIBRATION_SHADING_LS_A_B_STOP   = _CALIBRATION_SHADING_LS_A_B_START + WDR_MODE_COUNT,

	_CALIBRATION_SHADING_LS_TL84_R_START,
	_CALIBRATION_SHADING_LS_TL84_R_LINEAR = _CALIBRATION_SHADING_LS_TL84_R_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHADING_LS_TL84_R_WDR    = _CALIBRATION_SHADING_LS_TL84_R_START + WDR_MODE_POSITION,
	_CALIBRATION_SHADING_LS_TL84_R_STOP   = _CALIBRATION_SHADING_LS_TL84_R_START + WDR_MODE_COUNT,

	_CALIBRATION_SHADING_LS_TL84_G_START,
	_CALIBRATION_SHADING_LS_TL84_G_LINEAR = _CALIBRATION_SHADING_LS_TL84_G_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHADING_LS_TL84_G_WDR    = _CALIBRATION_SHADING_LS_TL84_G_START + WDR_MODE_POSITION,
	_CALIBRATION_SHADING_LS_TL84_G_STOP   = _CALIBRATION_SHADING_LS_TL84_G_START + WDR_MODE_COUNT,

	_CALIBRATION_SHADING_LS_TL84_B_START,
	_CALIBRATION_SHADING_LS_TL84_B_LINEAR = _CALIBRATION_SHADING_LS_TL84_B_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHADING_LS_TL84_B_WDR    = _CALIBRATION_SHADING_LS_TL84_B_START + WDR_MODE_POSITION,
	_CALIBRATION_SHADING_LS_TL84_B_STOP   = _CALIBRATION_SHADING_LS_TL84_B_START + WDR_MODE_COUNT,

	_CALIBRATION_SHADING_LS_D65_R_START,
	_CALIBRATION_SHADING_LS_D65_R_LINEAR = _CALIBRATION_SHADING_LS_D65_R_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHADING_LS_D65_R_WDR    = _CALIBRATION_SHADING_LS_D65_R_START + WDR_MODE_POSITION,
	_CALIBRATION_SHADING_LS_D65_R_STOP   = _CALIBRATION_SHADING_LS_D65_R_START + WDR_MODE_COUNT,

	_CALIBRATION_SHADING_LS_D65_G_START,
	_CALIBRATION_SHADING_LS_D65_G_LINEAR = _CALIBRATION_SHADING_LS_D65_G_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHADING_LS_D65_G_WDR    = _CALIBRATION_SHADING_LS_D65_G_START + WDR_MODE_POSITION,
	_CALIBRATION_SHADING_LS_D65_G_STOP   = _CALIBRATION_SHADING_LS_D65_G_START + WDR_MODE_COUNT,

	_CALIBRATION_SHADING_LS_D65_B_START,
	_CALIBRATION_SHADING_LS_D65_B_LINEAR = _CALIBRATION_SHADING_LS_D65_B_START + WDR_MODE_LINEAR,
	_CALIBRATION_SHADING_LS_D65_B_WDR    = _CALIBRATION_SHADING_LS_D65_B_START + WDR_MODE_POSITION,
	_CALIBRATION_SHADING_LS_D65_B_STOP   = _CALIBRATION_SHADING_LS_D65_B_START + WDR_MODE_COUNT,

	// non hdr settings
	_CALIBRATION_STITCHING_ERROR_THRESH,
	_CALIBRATION_MESH_SHADING_STRENGTH,
	_CALIBRATION_IRIDIX_RGB2REC709,
	_CALIBRATION_IRIDIX_REC709TORGB,
	_CALIBRATION_TEMPER_STRENGTH,
	_CALIBRATION_AE_EXPOSURE_CORRECTION,
	_CALIBRATION_IRIDIX_ASYMMETRY,
	_CALIBRATION_IRIDIX_BLACK_PRC,
	_CALIBRATION_IRIDIX_GAIN_MAX,
	_CALIBRATION_IRIDIX_MIN_MAX_STR,
	_CALIBRATION_IRIDIX_EV_LIM_FULL_STR,
	_CALIBRATION_LUXLOW_LUT,
	_CALIBRATION_MT_ABSOLUTE_LS_A_CCM_LINEAR,
	_CALIBRATION_MESH_COLOR_TEMPERATURE,
	_CALIBRATION_RGHIGH_LUT_MIN,
	_CALIBRATION_CT30POS,
	_CALIBRATION_MESH_LS_WEIGHT,
	_CALIBRATION_AWB_WARMING_LS_D50,
	_CALIBRATION_MT_ABSOLUTE_LS_D50_CCM_LINEAR,
	_CALIBRATION_MT_ABSOLUTE_LS_D40_CCM_LINEAR,
	_CALIBRATION_CT65POS,
	_CALIBRATION_AUTO_WB,
	_CALIBRATION_AWB_WARMING_LS_A,
	_CALIBRATION_CT_RG_POS_CALC,
	_CALIBRATION_RGHIGH_LUT_MAX,
	_CALIBRATION_RG_POS,
	_CALIBRATION_LUXLOW_LUT_STEP,
	_CALIBRATION_CT_BG_POS_CALC,
	_CALIBRATION_RGLOW_LUT_STEP,
	_CALIBRATION_WB_STRENGTH,
	_CALIBRATION_LUXLOW_LUT_MIN,
	_CALIBRATION_SKIN_TONE_CCM,
	_CALIBRATION_STATIC_WB,
	_CALIBRATION_AWB_WARMING_LS_D40,
	_CALIBRATION_COLOR_TEMP,
	_CALIBRATION_RGLOW_LUT_MIN,
	_CALIBRATION_MT_ABSOLUTE_LS_D40_CCM_HDR,
	_CALIBRATION_MESH_RGBG_WEIGHT,
	_CALIBRATION_LIGHT_SRC,
	_CALIBRATION_RGLOW_LUT_MAX,
	_CALIBRATION_CT40POS,
	_CALIBRATION_MT_ABSOLUTE_LS_A_CCM_HDR,
	_CALIBRATION_EVTOLUX_LUX_LUT,
	_CALIBRATION_LUXHIGH_LUT_STEP,
	_CALIBRATION_RGHIGH_LUT,
	_CALIBRATION_LUXLOW_LUT_MAX,
	_CALIBRATION_SKY_LUX_TH,
	_CALIBRATION_RGLOW_LUT,
	_CALIBRATION_MT_ABSOLUTE_LS_D50_CCM_HDR,
	_CALIBRATION_LUXHIGH_LUT_MIN,
	_CALIBRATION_BG_POS,
	_CALIBRATION_LUXHIGH_LUT_MAX,
	_CALIBRATION_LUXHIGH_LUT,
	_CALIBRATION_RGHIGH_LUT_STEP,
	_CALIBRATION_AWB_SCENE_PRESETS,
	_CALIBRATION_CNR_UV_DELTA12_SLOPE,
	_CALIBRATION_AF_MIN_TABLE,
	_CALIBRATION_AF_MAX_TABLE,
	_CALIBRATION_AF_WINDOW_RESIZE_TABLE,
	_CALIBRATION_EXP_RATIO_TABLE,
	_CALIBRATION_IRIDIX_STRENGTH_TABLE,
	_CALIBRATION_AWB_AVG_COEF,
	_CALIBRATION_IRIDIX_AVG_COEF,
	_CALIBRATION_AE_EXPOSURE_AVG_COEF,
	_CALIBRATION_CCM_ONE_GAIN_THRESHOLD,
	_CALIBRATION_NP_LUT_MEAN,
	_CALIBRATION_EVTOLUX_PROBABILITY_ENABLE,
	_CALIBRATION_DEFECT_PIXELS,
	_CALIBRATION_FLASH_RG,
	_CALIBRATION_FLASH_BG,
	_CALIBRATION_AF_LMS,
	_CALIBRATION_SINTER_RADIAL_LUT,
	_CALIBRATION_SINTER_RADIAL_PARAMS,
	_CALIBRATION_GDC_CONFIG,
	_CALIBRATION_BLACK_LEVEL_FS,
	_CALIBRATION_RGB2YUV_CONVERSION,
	_CALIBRATION_TOTAL_SIZE
} ;



typedef struct _ApicalCalibrations {
	LookupTable* calibrations[ _CALIBRATION_TOTAL_SIZE ] ;
} ApicalCalibrations ;


#endif // __APICAL_ISP_CALIBRATIONS_H__

