
# Makefile for OSS/VxWorks
#

CPU		= I80486
TOOL		= gnu

include $(WIND_BASE)/target/h/make/defs.bsp
include $(WIND_BASE)/target/h/make/make.$(CPU)$(TOOL)
include $(WIND_BASE)/target/h/make/defs.$(WIND_HOST_TYPE)

exe: vplay.o
