/* This file is automatically generated.
   This file selects the right generated file of `__stub_FUNCTION' macros
   based on the architecture being compiled for.  */

#include <sgidefs.h>

#if _MIPS_SIM == _MIPS_SIM_ABI32
# include <gnu/stubs-o32.h>
#endif
#if _MIPS_SIM == _MIPS_SIM_NABI32
# include <gnu/stubs-n32.h>
#endif
#if _MIPS_SIM == _MIPS_SIM_ABI64
# include <gnu/stubs-n64.h>
#endif
