// ------------------------------------------------------------------------------ //
//     This confidential and proprietary software/information may be used only    //
//        as authorized by a licensing agreement from Apical Limited              //
//                                                                                //
//                   (C) COPYRIGHT 2014 Apical Limited                            //
//                          ALL RIGHTS RESERVED                                   //
//                                                                                //
//      The entire notice above must be reproduced on all authorized              //
//       copies and copies may only be made to the extent permitted               //
//             by a licensing agreement from Apical Limited.                      //
//                                                                                //
// ------------------------------------------------------------------------------ //


//--------------------------------------------------------------------------------//
//----------------Generated by API compiler - do not edit-------------------------//
//--------------------------------------------------------------------------------//


#ifndef _APICAL_COMMAND_API_H_
#define _APICAL_COMMAND_API_H_
#include <apical-isp/apical_types.h>


// ------------------------------------------------------------------------------ //
//		COMMAND TYPE LIST
// ------------------------------------------------------------------------------ //
#define TSELFTEST                                         0x00000000
#define TSYSTEM                                           0x00000001
#define TIMAGE                                            0x00000002
#define TALGORITHMS                                       0x00000003
#define TSCENE_MODES                                      0x00000004
#define TREGISTERS                                        0x00000005
#define CALIBRATION                                       0x00000006


// ------------------------------------------------------------------------------ //
//		COMMAND LIST
// ------------------------------------------------------------------------------ //
#define SENSOR_ID                                         0x00000000
#define SENSOR_INTERFACE                                  0x00000001
#define ISP_INTERFACE                                     0x00000002
#define LENS_INTERFACE                                    0x00000003
#define ISP_REVISION                                      0x00000004
#define FW_REVISION                                       0x00000005
#define API_REVISION                                      0x00000006
#define CALIBRATION_REVISION                              0x00000007
#define BUFFER_DATA_TYPE                                  0x00000008
#define ISP_SYSTEM_STATE                                  0x00000009
#define TEST_PATTERN_ENABLE_ID                            0x0000000A
#define TEST_PATTERN_MODE_ID                              0x0000000B
#define SYSTEM_FREEZE_FIRMWARE                            0x0000000C
#define SYSTEM_MANUAL_EXPOSURE                            0x0000000D
#define SYSTEM_MANUAL_EXPOSURE_RATIO                      0x0000000E
#define SYSTEM_MANUAL_INTEGRATION_TIME                    0x0000000F
#define SYSTEM_MANUAL_SENSOR_ANALOG_GAIN                  0x00000010
#define SYSTEM_MANUAL_SENSOR_DIGITAL_GAIN                 0x00000011
#define SYSTEM_MANUAL_ISP_DIGITAL_GAIN                    0x00000012
#define SYSTEM_MANUAL_DIRECTIONAL_SHARPENING              0x00000013
#define SYSTEM_MANUAL_UN_DIRECTIONAL_SHARPENING           0x00000014
#define SYSTEM_MANUAL_IRIDIX                              0x00000015
#define SYSTEM_DIS_X                                      0x00000016
#define SYSTEM_DIS_Y                                      0x00000017
#define SYSTEM_MANUAL_SINTER                              0x00000018
#define SYSTEM_MANUAL_TEMPER                              0x00000019
#define SYSTEM_MANUAL_AWB                                 0x0000001A
#define SYSTEM_SLOW_FRAME_RATE_ENABLE                     0x0000001B
#define SYSTEM_MANUAL_SATURATION                          0x0000001C
#define SYSTEM_MANUAL_EXPOSURE_TIME                       0x0000001D
#define SYSTEM_EXPOSURE_DARK_TARGET                       0x0000001E
#define SYSTEM_EXPOSURE_BRIGHT_TARGET                     0x0000001F
#define SYSTEM_EXPOSURE_RATIO                             0x00000020
#define SYSTEM_MAX_EXPOSURE_RATIO                         0x00000021
#define SYSTEM_INTEGRATION_TIME                           0x00000022
#define SYSTEM_MAX_INTEGRATION_TIME                       0x00000023
#define SYSTEM_SENSOR_ANALOG_GAIN                         0x00000024
#define SYSTEM_MAX_SENSOR_ANALOG_GAIN                     0x00000025
#define SYSTEM_SENSOR_DIGITAL_GAIN                        0x00000026
#define SYSTEM_MAX_SENSOR_DIGITAL_GAIN                    0x00000027
#define SYSTEM_ISP_DIGITAL_GAIN                           0x00000028
#define SYSTEM_MAX_ISP_DIGITAL_GAIN                       0x00000029
#define SYSTEM_DIRECTIONAL_SHARPENING_TARGET              0x0000002A
#define SYSTEM_MAXIMUM_DIRECTIONAL_SHARPENING             0x0000002B
#define SYSTEM_MINIMUM_DIRECTIONAL_SHARPENING             0x0000002C
#define SYSTEM_UN_DIRECTIONAL_SHARPENING_TARGET           0x0000002D
#define SYSTEM_MAXIMUM_UN_DIRECTIONAL_SHARPENING          0x0000002E
#define SYSTEM_MINIMUM_UN_DIRECTIONAL_SHARPENING          0x0000002F
#define SYSTEM_IRIDIX_STRENGTH_TARGET                     0x00000030
#define SYSTEM_MAXIMUM_IRIDIX_STRENGTH                    0x00000031
#define SYSTEM_MINIMUM_IRIDIX_STRENGTH                    0x00000032
#define SYSTEM_SINTER_THRESHOLD_TARGET                    0x00000033
#define SYSTEM_MAXIMUM_SINTER_STRENGTH                    0x00000034
#define SYSTEM_MINIMUM_SINTER_STRENGTH                    0x00000035
#define SYSTEM_TEMPER_THRESHOLD_TARGET                    0x00000036
#define SYSTEM_MAXIMUM_TEMPER_STRENGTH                    0x00000037
#define SYSTEM_MINIMUM_TEMPER_STRENGTH                    0x00000038
#define SYSTEM_AWB_RED_GAIN                               0x00000039
#define SYSTEM_AWB_BLUE_GAIN                              0x0000003A
#define SYSTEM_SATURATION_TARGET                          0x0000003B
#define SYSTEM_ANTI_FLICKER_FREQUENCY                     0x0000003C
#define SYSTEM_AE_COMPENSATION                            0x0000003D
#define SYSTEM_CALIBRATE_BAD_PIXELS                       0x0000003E
#define RESOLUTION_ACTIVE_IMAGE_ID                        0x0000003F
#define SENSOR_FPS_MODE_ID                                0x00000040
#define FR_PIPE_STATUS_ID                                 0x00000041
#define DS1_PIPE_STATUS_ID                                0x00000042
#define DS2_PIPE_STATUS_ID                                0x00000043
#define FPS_MODE_ID                                       0x00000044
#define WDR_MODE_ID                                       0x00000045
#define DVI_OUTPUT_ID                                     0x00000046
#define ORIENTATION_HFLIP_ID                              0x00000047
#define ORIENTATION_VFLIP_ID                              0x00000048
#define IMAGE_RESIZE_ENABLE_ID                            0x00000049
#define IMAGE_RESIZE_WIDTH_ID                             0x0000004A
#define IMAGE_RESIZE_HEIGHT_ID                            0x0000004B
#define IMAGE_CROP_XOFFSET_ID                             0x0000004C
#define IMAGE_CROP_YOFFSET_ID                             0x0000004D
#define HISTOGRAM_LUM_CAPTURE_ID                          0x0000004E
#define SD_CAPTURE_FRAMES_ID                              0x0000004F
#define SD_CAPTURE_RUN_ID                                 0x00000050
#define AF_MODE_ID                                        0x00000051
#define AF_RANGE_LOW_ID                                   0x00000052
#define AF_RANGE_HIGH_ID                                  0x00000053
#define AF_ROI_ID                                         0x00000054
#define AF_STATUS_ID                                      0x00000055
#define AE_MODE_ID                                        0x00000056
#define AE_SPLIT_PRESET_ID                                0x00000057
#define AE_GAIN_ID                                        0x00000058
#define AE_EXPOSURE_ID					  0x00000059
#define AE_ROI_ID					  0x0000005A
#define AE_COMPENSATION_ID				  0x0000005B
#define AE_FREEZE_ID					  0x0000005C
#define AE_INTEGRATOR_SET_ID				  0x0000005D
#define ANTIFOG_MODE_ID					  0x0000005E
#define ANTIFOG_PRESET_ID				  0x0000005F
#define AWB_MODE_ID					  0x00000060
#define AWB_RANGE_LOW_ID				  0x00000061
#define AWB_RANGE_HIGH_ID				  0x00000062
#define AWB_RGAIN_ID					  0x00000063
#define AWB_BGAIN_ID					  0x00000064
#define AWB_TEMPERATURE_ID				  0x00000065
#define AWB_ROI_ID					  0x00000066
#define AWB_FREEZE_ID					  0x00000067
#define ANTIFLICKER_MODE_ID				  0x00000068
#define IRIDIX_MODE_ID					  0x00000069
#define IRIDIX_STRENGTH_ID				  0x0000006A
#define DIS_MODE_ID					  0x0000006B
#define SINTER_MODE_ID					  0x0000006C
#define SINTER_STRENGTH_ID				  0x0000006D
#define TEMPER_MODE_ID					  0x0000006E
#define TEMPER_STRENGTH_ID				  0x0000006F
#define DEFECT_PIXEL_CALIBRATE_ID			  0x00000070
#define SCENE_MODE_ID					  0x00000071
#define COLOR_MODE_ID					  0x00000072
#define FR_OUTPUT_MODE_ID				  0x00000073
#define DS1_OUTPUT_MODE_ID				  0x00000074
#define DS2_OUTPUT_MODE_ID				  0x00000075
#define SHARPENING_STRENGTH_ID				  0x00000076
#define BRIGHTNESS_STRENGTH_ID				  0x00000077
#define CONTRAST_STRENGTH_ID				  0x00000078
#define SATURATION_STRENGTH_ID				  0x00000079
#define LED_FLASH_MODE_ID				  0x0000007A
#define LED_FLASH_TIMEE_ID				  0x0000007B
#define REGISTERS_ADDRESS_ID				  0x0000007C
#define REGISTERS_SIZE_ID				  0x0000007D
#define REGISTERS_SOURCE_ID				  0x0000007E
#define REGISTERS_VALUE_ID				  0x0000007F
#define EXPOSURE_LOG2_ID				  0x00000080
#define GAIN_LOG2_ID                                      0x00000081


// ------------------------------------------------------------------------------ //
//		VALUE LIST
// ------------------------------------------------------------------------------ //
#define PAUSE                                             0x00000000
#define RUN                                               0x00000001
#define ON                                                0x00000002
#define OFF                                               0x00000003
#define PREVIEW_RES_FPS_MAX                               0x00000004
#define FULL_RES_FPS_MAX                                  0x00000005
#define FPS5                                              0x00000006
#define FPS15                                             0x00000007
#define FPS25                                             0x00000008
#define FPS30                                             0x00000009
#define FPS50                                             0x0000000A
#define FPS60                                             0x0000000B
#define ENABLE                                            0x0000000C
#define DISABLE                                           0x0000000D
#define IMAGE_WDR_MODE_LINEAR                             0x0000000E
#define IMAGE_WDR_MODE_FS_HDR                             0x0000000F
#define DVI_OUTPUT_FR                                     0x00000010
#define DVI_OUTPUT_DS                                     0x00000011
#define DVI_OUTPUT_DS2                                    0x00000012
#define CROP_FR                                           0x00000013
#define CROP_DS                                           0x00000014
#define SCALER                                            0x00000015
#define CROP_DS2                                          0x00000016
#define SCALER2                                           0x00000017
#define DONE                                              0x00000018
#define AF_AUTO_SINGLE                                    0x00000019
#define AF_AUTO_CONTINUOUS                                0x0000001A
#define AF_AUTO_SINGLE_MACRO                              0x0000001B
#define AF_AUTO_CONTINUOUS_MACRO                          0x0000001C
#define AF_HYPER_FOCAL                                    0x0000001D
#define AF_INFINITY                                       0x0000001E
#define AF_ABORT                                          0x0000001F
#define AF_NOT_FOCUSED                                    0x00000020
#define AF_SUCCESS                                        0x00000021
#define AF_FAIL                                           0x00000022
#define AF_LOCKED                                         0x00000023
#define AF_RUNNING                                        0x00000024
#define AE_AUTO                                           0x00000025
#define AE_FULL_MANUAL                                    0x00000026
#define AE_MANUAL_GAIN                                    0x00000027
#define AE_MANUAL_EXPOSURE_TIME                           0x00000028
#define AE_SPLIT_BALANCED                                 0x00000029
#define AE_SPLIT_INTEGRATION_PRIORITY                     0x0000002A
#define FREEZE                                            0x0000002B
#define UNFREEZE					  0x0000002C
#define ANTIFOG_DISABLE				          0x0000002D
#define ANTIFOG_ENABLE					   0x0000002E
#define ANTIFOG_STRONG					   0x0000002F
#define ANTIFOG_MEDIUM					   0x00000030
#define ANTIFOG_WEAK					   0x00000031
#define AWB_AUTO					   0x00000032
#define AWB_MANUAL					   0x00000033
#define AWB_DAY_LIGHT					   0x00000034
#define AWB_CLOUDY					   0x00000035
#define AWB_INCANDESCENT				   0x00000036
#define AWB_FLOURESCENT				   0x00000037
#define AWB_TWILIGHT					   0x00000038
#define AWB_SHADE					   0x00000039
#define AWB_WARM_FLOURESCENT				   0x0000003A
#define MANUAL						   0x0000003B
#define UNLIMIT					   0x0000003C
#define HIGH						   0x0000003D
#define MEDIUM						   0x0000003E
#define LOW						   0x0000003F
#define AUTO						   0x00000040
#define DARK_PIXELS					   0x00000041
#define BRIGHT_PIXELS					   0x00000042
#define PORTRAIT					   0x00000043
#define LANDSCAPE					   0x00000044
#define NIGHT						   0x00000045
#define MOTION						   0x00000046
#define INDOOR						   0x00000047
#define BEACH_SNOW					   0x00000048
#define SUNSET						   0x00000049
#define DAWN						   0x0000004A
#define FIREWORKS					   0x0000004B
#define TEXT						   0x0000004C
#define CANDLE						   0x0000004D
#define NIGHT_PORTRAIT					   0x0000004E
#define NORMAL						   0x0000004F
#define BLACK_AND_WHITE				   0x00000050
#define NEGATIVE					   0x00000051
#define SEPIA						   0x00000052
#define VIVID						   0x00000053
#define RGB						   0x00000054
#define YUV444						   0x00000055
#define YUV422						   0x00000056
#define YUV420						   0x00000057
#define FLASH_DISABLE					   0x00000058
#define FLASH_CONTINUOUS				   0x00000059
#define FLASH_MODE1					   0x0000005A
#define SENSOR						   0x0000005B
#define LENS						   0x0000005C
#define ISP                                               0x0000005D
#define MIPI                                              0x0000005E


// ------------------------------------------------------------------------------ //
//		RETURN VALUES
// ------------------------------------------------------------------------------ //
#define SUCCESS                                           0x00000000
#define NOT_IMPLEMENTED                                   0x00000001
#define NOT_SUPPORTED                                     0x00000002
#define NOT_PERMITTED                                     0x00000003
#define NOT_EXISTS                                        0x00000004
#define FAIL                                              0x00000005


// ------------------------------------------------------------------------------ //
//		ERROR REASONS
// ------------------------------------------------------------------------------ //
#define ERR_UNKNOWN                                       0x00000000
#define ERR_BAD_ARGUMENT                                  0x00000001
#define ERR_WRONG_SIZE                                    0x00000002


// ------------------------------------------------------------------------------ //
//		CALIBRATION VALUES
// ------------------------------------------------------------------------------ //
#define CALIBRATION_LIGHT_SRC                             0x00000000
#define CALIBRATION_RG_POS                                0x00000001
#define CALIBRATION_BG_POS                                0x00000002
#define CALIBRATION_MESH_RGBG_WEIGHT                      0x00000003
#define CALIBRATION_MESH_LS_WEIGHT                        0x00000004
#define CALIBRATION_MESH_COLOR_TEMPERATURE                0x00000005
#define CALIBRATION_LUXLOW_LUT_MIN                        0x00000006
#define CALIBRATION_LUXLOW_LUT_MAX                        0x00000007
#define CALIBRATION_LUXLOW_LUT_STEP                       0x00000008
#define CALIBRATION_LUXLOW_LUT                            0x00000009
#define CALIBRATION_LUXHIGH_LUT_MIN                       0x0000000A
#define CALIBRATION_LUXHIGH_LUT_MAX                       0x0000000B
#define CALIBRATION_LUXHIGH_LUT_STEP                      0x0000000C
#define CALIBRATION_LUXHIGH_LUT                           0x0000000D
#define CALIBRATION_RGLOW_LUT_MIN                         0x0000000E
#define CALIBRATION_RGLOW_LUT_MAX                         0x0000000F
#define CALIBRATION_RGLOW_LUT_STEP                        0x00000010
#define CALIBRATION_RGLOW_LUT                             0x00000011
#define CALIBRATION_RGHIGH_LUT_MIN                        0x00000012
#define CALIBRATION_RGHIGH_LUT_MAX                        0x00000013
#define CALIBRATION_RGHIGH_LUT_STEP                       0x00000014
#define CALIBRATION_RGHIGH_LUT                            0x00000015
#define CALIBRATION_WB_STRENGTH                           0x00000016
#define CALIBRATION_SKY_LUX_TH                            0x00000017
#define CALIBRATION_CT_RG_POS_CALC                        0x00000018
#define CALIBRATION_CT_BG_POS_CALC                        0x00000019
#define CALIBRATION_COLOR_TEMP                            0x0000001A
#define CALIBRATION_CT65POS                               0x0000001B
#define CALIBRATION_CT40POS                               0x0000001C
#define CALIBRATION_CT30POS                               0x0000001D
#define CALIBRATION_EVTOLUX_EV_LUT_LINEAR                 0x0000001E
#define CALIBRATION_EVTOLUX_EV_LUT_FS_HDR                 0x0000001F
#define CALIBRATION_EVTOLUX_LUX_LUT                       0x00000020
#define CALIBRATION_BLACK_LEVEL_R_LINEAR                  0x00000021
#define CALIBRATION_BLACK_LEVEL_GR_LINEAR                 0x00000022
#define CALIBRATION_BLACK_LEVEL_GB_LINEAR                 0x00000023
#define CALIBRATION_BLACK_LEVEL_B_LINEAR                  0x00000024
#define CALIBRATION_STATIC_WB                             0x00000025
#define CALIBRATION_AUTO_WB                               0x00000026
#define CALIBRATION_SKIN_TONE_CCM                         0x00000027
#define CALIBRATION_MT_ABSOLUTE_LS_A_CCM_LINEAR           0x00000028
#define CALIBRATION_MT_ABSOLUTE_LS_D40_CCM_LINEAR         0x00000029
#define CALIBRATION_MT_ABSOLUTE_LS_D50_CCM_LINEAR         0x0000002A
#define CALIBRATION_MT_ABSOLUTE_LS_A_CCM_HDR              0x0000002B
#define CALIBRATION_MT_ABSOLUTE_LS_D40_CCM_HDR            0x0000002C
#define CALIBRATION_MT_ABSOLUTE_LS_D50_CCM_HDR            0x0000002D
#define CALIBRATION_SHADING_LS_A_R_LINEAR                 0x0000002E
#define CALIBRATION_SHADING_LS_A_G_LINEAR                 0x0000002F
#define CALIBRATION_SHADING_LS_A_B_LINEAR                 0x00000030
#define CALIBRATION_SHADING_LS_TL84_R_LINEAR              0x00000031
#define CALIBRATION_SHADING_LS_TL84_G_LINEAR              0x00000032
#define CALIBRATION_SHADING_LS_TL84_B_LINEAR              0x00000033
#define CALIBRATION_SHADING_LS_D65_R_LINEAR               0x00000034
#define CALIBRATION_SHADING_LS_D65_G_LINEAR               0x00000035
#define CALIBRATION_SHADING_LS_D65_B_LINEAR               0x00000036
#define CALIBRATION_SHADING_LS_A_R_WDR                    0x00000037
#define CALIBRATION_SHADING_LS_A_G_WDR                    0x00000038
#define CALIBRATION_SHADING_LS_A_B_WDR                    0x00000039
#define CALIBRATION_SHADING_LS_TL84_R_WDR                 0x0000003A
#define CALIBRATION_SHADING_LS_TL84_G_WDR                 0x0000003B
#define CALIBRATION_SHADING_LS_TL84_B_WDR                 0x0000003C
#define CALIBRATION_SHADING_LS_D65_R_WDR                  0x0000003D
#define CALIBRATION_SHADING_LS_D65_G_WDR                  0x0000003E
#define CALIBRATION_SHADING_LS_D65_B_WDR                  0x0000003F
#define CALIBRATION_AWB_WARMING_LS_A                      0x00000040
#define CALIBRATION_AWB_WARMING_LS_D40                    0x00000041
#define CALIBRATION_AWB_WARMING_LS_D50                    0x00000042
#define CALIBRATION_NOISE_PROFILE_LINEAR                  0x00000043
#define CALIBRATION_DEMOSAIC_LINEAR                       0x00000044
#define CALIBRATION_NOISE_PROFILE_FS_HDR                  0x00000045
#define CALIBRATION_DEMOSAIC_FS_HDR                       0x00000046
#define CALIBRATION_GAMMA_FE_0_FS_HDR                     0x00000047
#define CALIBRATION_GAMMA_FE_1_FS_HDR                     0x00000048
#define CALIBRATION_BLACK_LEVEL_R_FS_HDR                  0x00000049
#define CALIBRATION_BLACK_LEVEL_GR_FS_HDR                 0x0000004A
#define CALIBRATION_BLACK_LEVEL_GB_FS_HDR                 0x0000004B
#define CALIBRATION_BLACK_LEVEL_B_FS_HDR                  0x0000004C
#define CALIBRATION_GAMMA_LINEAR                          0x0000004D
#define CALIBRATION_GAMMA_FS_HDR                          0x0000004E
#define CALIBRATION_IRIDIX_RGB2REC709                     0x0000004F
#define CALIBRATION_IRIDIX_REC709TORGB                    0x00000050
#define CALIBRATION_IRIDIX_ASYMMETRY                      0x00000051
#define CALIBRATION_DEFECT_PIXELS                         0x00000052
//------------------ISP CALIBRATIONS-------------------
#define CALIBRATION_DP_SLOPE_LINEAR                       0x00000053
#define CALIBRATION_DP_SLOPE_FS_HDR                       0x00000054
#define CALIBRATION_DP_THRESHOLD_LINEAR                   0x00000055
#define CALIBRATION_DP_THRESHOLD_FS_HDR                   0x00000056
#define CALIBRATION_STITCHING_ERROR_THRESH                0x00000057
#define CALIBRATION_EVTOLUX_PROBABILITY_ENABLE            0x00000058
#define CALIBRATION_NP_LUT_MEAN                           0x00000059
#define CALIBRATION_AWB_AVG_COEF                          0x0000005A
#define CALIBRATION_IRIDIX_AVG_COEF                       0x0000005B
#define CALIBRATION_AE_EXPOSURE_AVG_COEF                  0x0000005C
#define CALIBRATION_CNR_UV_DELTA12_SLOPE                  0x0000005D
#define CALIBRATION_AF_MIN_TABLE                          0x0000005E
#define CALIBRATION_AF_MAX_TABLE                          0x0000005F
#define CALIBRATION_AF_WINDOW_RESIZE_TABLE                0x00000060
#define CALIBRATION_EXP_RATIO_TABLE                       0x00000061
#define CALIBRATION_IRIDIX_STRENGTH_MAXIMUM_LINEAR        0x00000062
#define CALIBRATION_IRIDIX_STRENGTH_MAXIMUM_WDR           0x00000063
#define CALIBRATION_IRIDIX_BLACK_PRC                      0x00000064
#define CALIBRATION_IRIDIX_GAIN_MAX                       0x00000065
#define CALIBRATION_IRIDIX_MIN_MAX_STR                    0x00000066
#define CALIBRATION_IRIDIX_EV_LIM_FULL_STR                0x00000067
#define CALIBRATION_IRIDIX_EV_LIM_NO_STR_LINEAR           0x00000068
#define CALIBRATION_IRIDIX_EV_LIM_NO_STR_FS_HDR           0x00000069
#define CALIBRATION_AE_CORRECTION_LINEAR                  0x0000006A
#define CALIBRATION_AE_CORRECTION_FS_HDR                  0x0000006B
#define CALIBRATION_AE_EXPOSURE_CORRECTION                0x0000006C
#define CALIBRATION_SINTER_STRENGTH_LINEAR                0x0000006D
#define CALIBRATION_SINTER_STRENGTH_FS_HDR                0x0000006E
#define CALIBRATION_SINTER_STRENGTH1_LINEAR               0x0000006F
#define CALIBRATION_SINTER_STRENGTH1_FS_HDR               0x00000070
#define CALIBRATION_SINTER_THRESH1_LINEAR                 0x00000071
#define CALIBRATION_SINTER_THRESH1_FS_HDR                 0x00000072
#define CALIBRATION_SINTER_THRESH4_LINEAR                 0x00000073
#define CALIBRATION_SINTER_THRESH4_FS_HDR                 0x00000074
#define CALIBRATION_SHARP_ALT_D_LINEAR                    0x00000075
#define CALIBRATION_SHARP_ALT_D_FS_HDR                    0x00000076
#define CALIBRATION_SHARP_ALT_UD_LINEAR                   0x00000077
#define CALIBRATION_SHARP_ALT_UD_FS_HDR                   0x00000078
#define CALIBRATION_SHARPEN_FR_LINEAR                     0x00000079
#define CALIBRATION_SHARPEN_FR_WDR                        0x0000007A
#define CALIBRATION_SHARPEN_DS1_LINEAR                    0x0000007B
#define CALIBRATION_SHARPEN_DS1_WDR                       0x0000007C
#define CALIBRATION_SHARPEN_DS2_LINEAR                    0x0000007D
#define CALIBRATION_SHARPEN_DS2_WDR                       0x0000007E
#define CALIBRATION_DEMOSAIC_NP_OFFSET_LINEAR             0x0000007F
#define CALIBRATION_DEMOSAIC_NP_OFFSET_FS_HDR             0x00000080
#define CALIBRATION_MESH_SHADING_STRENGTH                 0x00000081
#define CALIBRATION_SATURATION_STRENGTH_LINEAR            0x00000082
#define CALIBRATION_SATURATION_STRENGTH_FS_HDR            0x00000083
#define CALIBRATION_TEMPER_STRENGTH                       0x00000084
#define CALIBRATION_FLASH_RG                              0x00000085
#define CALIBRATION_FLASH_BG                              0x00000086
#define CALIBRATION_CCM_ONE_GAIN_THRESHOLD                0x00000087
#define CALIBRATION_AE_BALANCED_LINEAR                    0x00000088
#define CALIBRATION_AE_BALANCED_WDR                       0x00000089
#define CALIBRATION_IRIDIX_STRENGTH_TABLE                 0x0000008A
#define CALIBRATION_RGB2YUV_CONVERSION                    0x0000008B

#define API2FRM_SIZE 140
uint16_t* GET_API2FRM_IDX(void);
void apical_api_init_idx_array(void) ;



// ------------------------------------------------------------------------------ //
//		DIRECTION VALUES
// ------------------------------------------------------------------------------ //
#define COMMAND_SET                                       0x00000000
#define COMMAND_GET                                       0x00000001
#define API_VERSION                                       0x00000064

typedef struct {
	uint8_t type;
	uint8_t id;
	uint8_t dir;
	uint32_t value;
	uint32_t data_size;
} apical_api_control_t;

// ------------------------------------------------------------------------------ //
//		SET/GET FUNCTION
// ------------------------------------------------------------------------------ //
//set command: ret = apical_command(instance, TALGORITHMS, AF_MODE, AF_AUTO, COMMAND_SET, &RET_VALUE);
//get command: ret = apical_command(instance, TALGORITHMS, AF_MODE, AF_AUTO, COMMAND_GET, &RET_VALUE);
uint8_t apical_command(uint8_t command_type, uint8_t command, uint32_t value, uint8_t direction, uint32_t *ret_value);

#define APICAL_API_BUFFER_MAX_SIZE		1024
uint8_t* get_apical_api_buffer(void);
extern uint32_t apical_api_buffer_data_size;
uint32_t apical_api_read_buffer(uint8_t* buf);

uint8_t apical_api_calibration(uint8_t type, uint8_t direction, void* data, uint32_t data_size, uint32_t* ret_value);

#endif//_APICAL_COMMAND_API_H_
