
obj-y += ds-j801mb-misc.o ds-j801mb-pm.o ds-j801mb-lcd.o  

obj-$(CONFIG_I2C)		+= ds-j801mb-i2c.o
obj-$(CONFIG_MFD_ACT8600)	+= ds-j801mb-regulator.o
obj-$(CONFIG_MFD_RICOH618)	+= ds-j801mb-regulator.o
obj-$(CONFIG_MMC_JZ4780)	+= ds-j801mb-mmc.o
obj-$(CONFIG_JZ4780_INTERNAL_CODEC) += ds-j801mb-sound.o
