
obj-y += vga-dongle-misc.o vga-dongle-pm.o vga-dongle-lcd.o vga-dongle-regulator.o  

obj-$(CONFIG_I2C)		+= vga-dongle-i2c.o
#obj-$(CONFIG_MFD_ACT8600)	+= vga-dongle-regulator.o
obj-$(CONFIG_MMC_JZ4780)	+= vga-dongle-mmc.o
obj-$(CONFIG_JZ4780_INTERNAL_CODEC) += vga-dongle-sound.o
