#ifndef OSS_ERRNO_H
#define OSS_ERRNO_H

/*
 * Error (errno) codes used by OSS.
 * 
 * This file is automatically generated by srcconf.c (produce_errno_h()) - do not edit.
 * 
 * The following codes are derived from the system dependent
 * error numbers defined in <errno.h>
 */

#define OSS_E2BIG		-7
#define OSS_EACCES		-13
#define OSS_EAGAIN		-11
#define OSS_EBADE		-52
#define OSS_EBUSY		-16
#define OSS_ECONNRESET		-104
#define OSS_EDOM		-33
#define OSS_EFAULT		-14
#define OSS_EIDRM		-43
#define OSS_EINTR		-4
#define OSS_EINVAL		-22
#define OSS_EIO		-5
#define OSS_ELOOP		-40
#define OSS_ENODEV		-19
#define OSS_ENOENT		-2
#define OSS_ENOMEM		-12
#define OSS_ENOSPC		-28
#define OSS_ENOTSUP		-95
#define OSS_ENXIO		-6
#define OSS_EPERM		-1
#define OSS_EPIPE		-32
#define OSS_ERANGE		-34
#define OSS_EWOULDBLOCK		-11

#endif
