#!/bin/sh
OSSLIBDIR=/usr/lib/oss
if [ -e /etc/oss.conf ]; then . /etc/oss.conf; fi
if [ -e /tmp/OSS_UPGRADE ]; then echo "Upgrading OSS - will not purge $OSSLIBDIR."; else rm -rf "$OSSLIBDIR"/*; fi
rm -f /usr/lib/libflashsupport.so
if [ -x /usr/bin/update-menus ]; then /usr/bin/update-menus; fi
